// Scientific Terms Database - English to Arabic
const scientificTerms = {
    // Basic Science Terms
    "science": "علم",
    "research": "بحث",
    "experiment": "تجربة",
    "hypothesis": "فرضية",
    "theory": "نظرية",
    "laboratory": "مختبر",
    "analysis": "تحليل",
    "synthesis": "تركيب",
    "observation": "ملاحظة",
    "conclusion": "استنتاج",
    "method": "منهج",
    "data": "بيانات",
    "evidence": "دليل",
    "result": "نتيجة",
    "variable": "متغير",
    "constant": "ثابت",
    "measurement": "قياس",
    "calculation": "حساب",
    "experiment": "تجربة",
    "investigation": "تحقيق",
    "discovery": "اكتشاف",

    // Biology Terms
    "biology": "علم الأحياء",
    "cell": "خلية",
    "organism": "كائن حي",
    "molecule": "جزيء",
    "protein": "بروتين",
    "dna": "حمض نووي",
    "gene": "جين",
    "chromosome": "كروموسوم",
    "enzyme": "إنزيم",
    "metabolism": "استقلاب",
    "photosynthesis": "تمثيل ضوئي",
    "respiration": "تنفس",
    "evolution": "تطور",
    "genetics": "علم الوراثة",
    "ecology": "علم البيئة",
    "microbiology": "علم الأحياء الدقيقة",
    "botany": "علم النبات",
    "zoology": "علم الحيوان",
    "anatomy": "تشريح",
    "physiology": "فسلجة",
    "bacteria": "بكتيريا",
    "virus": "فيروس",
    "tissue": "نسيج",
    "organ": "عضو",
    "species": "نوع",
    "population": "مجتمع",
    "ecosystem": "نظام بيئي",
    "habitat": "موطن",
    "adaptation": "تكيف",
    "mutation": "طفرة",
    "natural selection": "الانتقاء الطبيعي",

    // Chemistry Terms
    "chemistry": "كيمياء",
    "atom": "ذرة",
    "element": "عنصر",
    "compound": "مركب",
    "molecule": "جزيء",
    "reaction": "تفاعل",
    "catalyst": "محفز",
    "acid": "حمض",
    "base": "قاعدة",
    "ph": "درجة الحموضة",
    "solution": "محلول",
    "solvent": "مذيب",
    "solute": "مذاب",
    "concentration": "تركيز",
    "molarity": "مولارية",
    "stoichiometry": "الكيمياء التوازنية",
    "equilibrium": "توازن",
    "oxidation": "أكسدة",
    "reduction": "اختزال",
    "valence": "تكافؤ",
    "periodic table": "الجدول الدوري",
    "electron": "إلكترون",
    "proton": "بروتون",
    "neutron": "نيوترون",
    "nucleus": "نواة",
    "orbital": "مدار",
    "bond": "رابطة",
    "ionic": "أيوني",
    "covalent": "تساهمي",
    "metallic": "فلزي",
    "organic": "عضوي",
    "inorganic": "غير عضوي",
    "polymer": "بوليمر",
    "crystal": "بلورة",
    "distillation": "تقطير",
    "filtration": "ترشيح",
    "chromatography": "كروماتوغرافيا",

    // Physics Terms
    "physics": "فيزياء",
    "force": "قوة",
    "energy": "طاقة",
    "work": "شغل",
    "power": "قدرة",
    "motion": "حركة",
    "velocity": "سرعة",
    "acceleration": "تسارع",
    "momentum": "زخم",
    "mass": "كتلة",
    "weight": "وزن",
    "gravity": "جاذبية",
    "friction": "احتكاك",
    "pressure": "ضغط",
    "density": "كثافة",
    "temperature": "حرارة",
    "heat": "حرارة",
    "wave": "موجة",
    "frequency": "تردد",
    "amplitude": "سعة",
    "wavelength": "طول موجة",
    "sound": "صوت",
    "light": "ضوء",
    "electricity": "كهرباء",
    "magnetism": "مغناطيسية",
    "circuit": "دائرة",
    "voltage": "فولتية",
    "current": "تيار",
    "resistance": "مقاومة",
    "ohm": "أوم",
    "watt": "واط",
    "joule": "جول",
    "newton": "نيوتن",
    "tesla": "تسلا",
    "hertz": "هرتز",
    "electromagnetic": "كهرومغناطيسي",
    "quantum": "كمي",
    "relativity": "نسبية",
    "thermodynamics": "الديناميكا الحرارية",
    "optics": "بصريات",
    "mechanics": "ميكانيكا",
    "nuclear": "نووي",
    "atomic": "ذري",
    "particle": "جسيم",
    "field": "حقل",
    "potential": "جهد",
    "kinetic": "حركي",

    // Mathematics Terms
    "mathematics": "رياضيات",
    "equation": "معادلة",
    "function": "دالة",
    "variable": "متغير",
    "constant": "ثابت",
    "derivative": "مشتقة",
    "integral": "تكامل",
    "limit": "نهاية",
    "matrix": "مصفوفة",
    "vector": "متجه",
    "scalar": "عدد",
    "geometry": "هندسة",
    "algebra": "جبر",
    "calculus": "حساب تفاضلي",
    "statistics": "إحصاء",
    "probability": "احتمال",
    "theorem": "مبرهنة",
    "proof": "برهان",
    "hypothesis": "فرضية",
    "correlation": "ارتباط",
    "regression": "انحدار",
    "distribution": "توزيع",
    "median": "وسيط",
    "mean": "متوسط",
    "mode": "منوال",
    "standard deviation": "انحراف معياري",
    "graph": "رسم بياني",
    "chart": "مخطط",
    "axis": "محور",
    "coordinate": "إحداثية",
    "angle": "زاوية",
    "triangle": "مثلث",
    "circle": "دائرة",
    "square": "مربع",
    "rectangle": "مستطيل",
    "polygon": "مضلع",
    "diameter": "قطر",
    "radius": "نصف قطر",
    "circumference": "محيط",
    "area": "مساحة",
    "volume": "حجم",
    "perimeter": "محيط",

    // Computer Science Terms
    "computer": "حاسوب",
    "program": "برنامج",
    "algorithm": "خوارزمية",
    "data": "بيانات",
    "software": "برنامج",
    "hardware": "عتاد",
    "network": "شبكة",
    "internet": "إنترنت",
    "database": "قاعدة بيانات",
    "programming": "برمجة",
    "code": "كود",
    "function": "دالة",
    "variable": "متغير",
    "loop": "حلقة",
    "condition": "شرط",
    "array": "مصفوفة",
    "string": "سلسلة",
    "integer": "عدد صحيح",
    "float": "عدد عشري",
    "boolean": "منطقي",
    "object": "كائن",
    "class": "فئة",
    "method": "طريقة",
    "interface": "واجهة",
    "protocol": "بروتوكول",
    "server": "خادم",
    "client": "عميل",
    "browser": "متصفح",
    "cache": "ذاكرة مؤقتة",
    "memory": "ذاكرة",
    "processor": "معالج",
    "file": "ملف",
    "directory": "دليل",
    "operating system": "نظام تشغيل",
    "artificial intelligence": "ذكاء اصطناعي",
    "machine learning": "تعلم آلي",
    "neural network": "شبكة عصبية",
    "deep learning": "تعلم عميق",

    // University Terms
    "university": "جامعة",
    "faculty": "كلية",
    "department": "قسم",
    "professor": "أستاذ",
    "lecturer": "محاضر",
    "student": "طالب",
    "course": "مقرر",
    "lecture": "محاضرة",
    "tutorial": "درس خصوصي",
    "seminar": "حلقة دراسية",
    "laboratory": "مختبر",
    "assignment": "واجب",
    "exam": "امتحان",
    "quiz": "اختبار",
    "grade": "درجة",
    "degree": "شهادة",
    "bachelor": "بكالوريوس",
    "master": "ماجستير",
    "doctorate": "دكتوراه",
    "thesis": "رسالة",
    "dissertation": "أطروحة",
    "research": "بحث",
    "publication": "منشور",
    "journal": "مجلة",
    "conference": "مؤتمر",
    "scholarship": "منحة",
    "tuition": "رسوم",
    "semester": "فصل دراسي",
    "academic": "أكاديمي",
    "scientific": "علمي"
};

// Common scientific phrases and expressions
const scientificPhrases = {
    "scientific method": "المنهج العلمي",
    "peer review": "مراجعة الأقران",
    "literature review": "مراجعة الأدبيات",
    "research methodology": "منهجية البحث",
    "data analysis": "تحليل البيانات",
    "statistical significance": "الدلالة الإحصائية",
    "control group": "مجموعة ضابطة",
    "experimental group": "مجموعة تجريبية",
    "null hypothesis": "الفرضية الصفرية",
    "alternative hypothesis": "الفرضية البديلة",
    "confidence interval": "فترة ثقة",
    "error margin": "هامش خطأ",
    "sample size": "حجم العينة",
    "random sampling": "عينة عشوائية",
    "blind study": "دراسة عمياء",
    "double-blind study": "دراسة عمياء مزدوجة",
    "placebo effect": "تأثير الدواء الوهمي",
    "side effects": "آثار جانبية",
    "clinical trial": "تجربة سريرية",
    "informed consent": "موافقة مسبقة",
    "ethical considerations": "اعتبارات أخلاقية"
};

// Export for use in the application
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { scientificTerms, scientificPhrases };
}